import styles from '../../styles/AdDetails.module.css';
import Head from 'next/head';
import Link from 'next/link';

export default function AdDetails({ data: ad }) {
  console.log(ad);
  const { title, description, price, condition, image_url, user } = ad;
  // const { username, email, _id } = user;
  return (
    <div className="container">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.ad}>
        <h1>{title}</h1>
        <hr />
        <div className={styles.ad_image}>
          <img src={image_url} alt="ad image" />
        </div>

        <div>
          <div className="price">$ {price}</div>
          <div className={styles.condition}>{condition}</div>
        </div>
        <hr />
        <div className={styles.description}>
          <h3>Description</h3>
          {description}
        </div>
      </div>
      <div className={styles.user}>
        {/* {link to profile} */}
        {/* <div>{username}</div>
        <div>{email}</div> */}
        {/* <Link to={`/users/${_id}`}> */}
        <a>
          {/* <div>{username}</div> */}
          <div>John Doe</div>
        </a>
        {/* </Link> */}
        {/* <div>{email}</div> */}
        <div>john.doe@ttt.com</div>
        <button>Chat</button>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { id } = context.params;
  const res = await fetch(`http://localhost:5000/api/ads/${id}`);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data },
  };
}
