@hostname = http://localhost:5000/api/ads

GET {{hostname}}
Content-Type: application/json
###

GET {{hostname}}/61a27d1bbe33ee125636fd2c
Content-Type: application/json
###


POST {{hostname}}
Content-Type: application/json

{
  "title": "Specialized Crossroads",
  "description": "New Bike",
  "condition": "New"
}