@hostname = http://localhost:5000/api/auth


POST {{hostname}}/register
Content-Type: application/json

{
  "username": "Banks",
  "email": "ttt@ksdfn.com",
  "password": "new"
}


POST {{hostname}}/login
Content-Type: application/json

{
    "username": "Banks",
    "password": "new"

}

