import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Ads from '../components/Ads/Ads';

export default function Home({ data: ads }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Ads ads={ads} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch(`http://localhost:5000/api/ads`);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data },
  };
}
